import type {Metadata} from 'next';
import './globals.css';
import ClientLayout from './ClientLayout'; // Ensure this path is correct

export const metadata: Metadata = {
  title: 'PX',
  description: 'Generated by Firebase Studio',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* Body class will be applied by ClientLayout to avoid hydration mismatch */}
      <body> 
        <ClientLayout>
          {children}
        </ClientLayout>
      </body>
    </html>
  );
}
